[package]
name = "nenuphar"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
gtk = { version = "0.10.0", package = "gtk4", features = ["v4_12"] }
input = "0.9.1"
libc = "0.2.175"

